SCENARIO_RULE_CONFIG = {
    "trucks_encountered_during_construction": {
        "enabled": True,
        "approach_speed": 3.0,
        "interaction_speed": 2.2,
        "max_throttle": 0.24,
        "recovery_throttle": 0.28,
        "obstacle_confidence": 0.30,
        "steer_scale": 1.0,
        "steer_smoothing": 0.72,
        "construction_steer_bias": 0.0,
        "construction_steer_limit": 0.24,
        "brake_near_obstacle": 0.65,
        "near_obstacle_distance": 7.5,
        "hold_frames": 25,
        "min_confidence": 0.70,
    },
    "high_speed_temporary_construction": {
        "enabled": True,
        "approach_speed": 6.0,
        "interaction_speed": 4.0,
        "obstacle_confidence": 0.35,
        "steer_scale": 0.75,
        "hold_frames": 25,
        "min_confidence": 0.70,
    },
    "roundabout": {
        "enabled": True,
        "approach_speed": 5.0,
        "yield_speed": 2.0,
        "enter_speed": 4.0,
        "ttc_yield": 4.0,
        "hold_frames": 15,
        "min_confidence": 0.70,
    },
}
